# These settings are synced to GitHub by https://probot.github.io/apps/settings/
# pliancy/.github:.github/settings.yaml

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: intune-node

  # A short description of the repository that will show up on GitHub
  description: NodeJS API wrapper for Intune
  
  # A URL with more information about the repository
  homepage: https://www.npmjs.com/package/microsoft-intune

  # A comma-separated list of topics to set on the repository
  topics: nodejs, module, microsoft, microsoft-intune
